# NumPy - tablice cześć 2 - zadania

In [ ]:
import numpy as np

## Numpy Indexing

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Stwórz ``result: ndarray``
1. Dodaj do ``result`` elementy z ``DATA`` o indeksach:

    * wiersz 0, kolumna 2
    * wiersz 2, kolumna 2
    * wiersz 0, kolumna 0
    * wiersz 1, kolumna 0

1. Rozmiar ``result`` musi być 2x2
1. Typ ``result`` musi być float
1. Porównaj wyniki z sekcją "Output" (patrz poniżej)

Output:
```python
result: ndarray
# array([[3., 9.],
#        [1., 4.]])
```

Hint:
* ``np.zeros(shape, dtype)``

In [ ]:
DATA = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Numpy Slice 1

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Wybierz wewnętrzne 2x2 elementy
1. Porównaj wyniki z sekcją "Output" (patrz poniżej)

Output:
```python
result: ndarray
# array([[8, 4],
#        [5, 2]])
```

In [ ]:
DATA = np.array([
    [2, 8, 1, 5],
    [8, 8, 4, 4],
    [5, 5, 2, 5],
    [1, 0, 6, 0],
])

## Numpy Slice 2

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Wypisz środkowe 4x4 elementy
1. Środkowa macierz jest dokładnie w środku większej

Output:
```python
result: ndarray
# array([[2, 0, 7, 5],
#        [1, 2, 9, 1],
#        [8, 8, 8, 2],
#        [4, 3, 6, 9]])
```

![Inner 4x4 elements](img/inner-square.png)

In [ ]:
DATA = np.array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6, 8, 8, 1, 6],
                 [7, 7, 8, 1, 5, 9, 8, 9, 4, 3, 0, 3, 5, 0, 2, 3],
                 [8, 1, 3, 3, 3, 7, 0, 1, 9, 9, 0, 4, 7, 3, 2, 7],
                 [2, 0, 0, 4, 5, 5, 6, 8, 4, 1, 4, 9, 8, 1, 1, 7],
                 [9, 9, 3, 6, 7, 2, 0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
                 [4, 4, 8, 4, 3, 7, 5, 5, 0, 1, 5, 9, 3, 0, 5, 0],
                 [1, 2, 4, 2, 0, 3, 2, 0, 7, 5, 9, 0, 2, 7, 2, 9],
                 [2, 3, 3, 2, 3, 4, 1, 2, 9, 1, 4, 6, 8, 2, 3, 0],
                 [0, 6, 0, 6, 3, 3, 8, 8, 8, 2, 3, 2, 0, 8, 8, 3],
                 [8, 2, 8, 4, 3, 0, 4, 3, 6, 9, 8, 0, 8, 5, 9, 0],
                 [9, 6, 5, 3, 1, 8, 0, 4, 9, 6, 5, 7, 8, 8, 9, 2],
                 [8, 6, 6, 9, 1, 6, 8, 8, 3, 2, 3, 6, 3, 6, 5, 7],
                 [0, 8, 4, 6, 5, 8, 2, 3, 9, 7, 5, 3, 4, 5, 3, 3],
                 [7, 9, 9, 9, 7, 3, 2, 3, 9, 7, 7, 5, 1, 2, 2, 8],
                 [1, 5, 8, 4, 0, 2, 5, 5, 0, 8, 1, 1, 0, 3, 8, 8],
                 [4, 4, 0, 9, 3, 7, 3, 2, 1, 1, 2, 1, 4, 2, 5, 5]])

## Numpy Round Rint
1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Zaokrąglij wartości do pełnych liczb całkowitych
1. Przekonwertuj typ danych do ``np.int8``
1. Porównaj wyniki z sekcją "Output" (patrz poniżej)

Output:
```python
result: ndarray
# array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1], dtype=int8)
```

In [ ]:
DATA = np.array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
                 0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
                 0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
                 0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
                 0.97861834])

## Numpy Round Floor and Ceil

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Zaokrąglij wartości ``data`` w górę (ceil) i je wypisz
1. Zaokrąglij wartości ``data`` w dół (floor) i je wypisz
1. Zaokrąglij wartości ``data`` i je wypisz
1. Porównaj wyniki z sekcją "Output" (patrz poniżej)

Output:
```python

ceil: ndarray
# array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
#        1., 1., 1., 1.])

floor: ndarray
# array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#        0., 0., 0., 0.])

round: ndarray
# array([1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
#        1., 1., 1., 1.])
```

In [ ]:
DATA = np.array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
                 0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
                 0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
                 0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
                 0.97861834])

## Numpy Round Clip

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Stwórz `result: ndarray` z kopią danych z `DATA`
1. Przytnij liczby w pierwszej kolumnie od 50 (włącznie) do 80 (rozłącznie)
1. Wypisz ``result``
1. Porównaj wyniki z sekcją "Output" (patrz poniżej)

Output:
```python
result: ndarray
# array([[50, 47, 64],
#        [67, 67,  9],
#        [79, 21, 36],
#        [79, 70, 88],
#        [79, 12, 58],
#        [65, 39, 87],
#        [50, 88, 81]])
```

In [ ]:
DATA = np.array([[44, 47, 64],
                 [67, 67,  9],
                 [83, 21, 36],
                 [87, 70, 88],
                 [88, 12, 58],
                 [65, 39, 87],
                 [46, 88, 81]])

## Numpy Sort

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Posortuj kolumny ``result``
1. Flipnij wiersze ``result``
1. Wypisz ``result``    

Output:
```python
result: ndarray
# array([[36, 70, 87, 88],
#        [ 9, 21, 67, 83],
#        [44, 47, 64, 67]])
```

In [ ]:
DATA = np.array([[44, 47, 64, 67],
                 [67,  9, 83, 21],
                 [36, 87, 70, 88]])

## Numpy Methods

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Zmień kształt na 3x4
1. Wypełnij ostatnią kolumnę zerami (0)
1. Transponuj ``result``
1. Przekonwertuj ``result`` do float
1. Wypełnij pierwszy wiersz ``np.nan``
1. Wypisz ``result``

Output:
```python
result: ndarray
# array([[nan, nan, nan],
#        [47.,  9., 87.],
#        [64., 83., 70.],
#        [ 0.,  0.,  0.]])
```

In [ ]:
DATA = np.array([[44, 47, 64, 67],
                 [67,  9, 83, 21],
                 [36, 87, 70, 88]])