# NumPy - Zaawansowane Indeksowanie - lekcja

In [1]:
import numpy as np

## Unique

In [7]:
a = np.array([[1, 2, 3, 1],
              [1, 4, 5, 6]])

np.unique(a).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## Nonzero

In [8]:
a = np.array([[1, 0, 2],
              [3, 0, 4]])

np.nonzero(a)

# (array([0, 0, 1, 1]),
#  array([0, 2, 0, 2]))

(array([0, 0, 1, 1]), array([0, 2, 0, 2]))

## Where

- jeden argument
- wiele argumentów


In [24]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[1, 2, 3],
              [4, 5, 6]])

c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

d = np.array([[1, 1, 3],
              [4, 0, 6],
              [2, 7, 9]])

np.where( c>5, np.nan, d)

array([[ 1.,  1.,  3.],
       [ 4.,  0., nan],
       [nan, nan, nan]])

## Zaawansowane Indeksowanie

In [26]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


a[ a > a.mean()+1 ]

array([7, 8, 9])

In [27]:
even = (a % 2 == 0)

a[even]

array([2, 4, 6, 8])

In [28]:
a[ (a>2) & (a<=5) & (a%2==1) ]

array([3, 5])

In [29]:
query1 = ( a > 2)
query2 = ( a <= 5)
query3 = ( a % 2 == 1)


a[ query1 & query2 & query3 ]

array([3, 5])

In [37]:
# '2000-01-01' -> [1, 2, 3]
# '2000-01-02' -> [4, 5, 6]
# '2000-01-03' -> [7, 8, 9]


date = np.array([
    '2000-01-01',
    '2000-01-02',
    '2000-01-03'])

values = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


jan01 = (date == '2000-01-01')
jan03 = (date == '2000-01-03')


values[ jan01 | jan03, :2 ] = 0

values

array([[0, 0, 3],
       [4, 5, 6],
       [0, 0, 9]])

In [45]:
#                Morning         Noon      Evening
# 1999-12-30  1.76405235,  0.40015721,  0.97873798,
# 1999-12-31  2.2408932 ,  1.86755799, -0.97727788,
# 2000-01-01  0.95008842, -0.15135721, -0.10321885,
# 2000-01-02  0.4105985 ,  0.14404357,  1.45427351,


index = np.array([
    '1999-12-30',
    '1999-12-31',
    '2000-01-01',
    '2000-01-02'])

columns = np.array(['Morning', 'Noon', 'Evening'])


data = np.array([[ 1.76405235,  0.40015721,  0.97873798],
                 [ 2.2408932 ,  1.86755799, -0.97727788],
                 [ 0.95008842, -0.15135721, -0.10321885],
                 [ 0.4105985 ,  0.14404357,  1.45427351]])


dec31 = (index == '1999-12-31')
jan01 = (index == '2000-01-01')
morning = (columns == 'Morning')
evening = (columns == 'Evening')


data[ (dec31|jan01), (morning|evening)]

array([ 2.2408932 , -0.10321885])

In [40]:
data[ (index == '1999-12-31'), (columns == 'Morning') ]

array([2.2408932])

In [46]:
data[np.ix_((dec31|jan01), (morning|evening))]

array([[ 2.2408932 , -0.97727788],
       [ 0.95008842, -0.10321885]])